### ISSUE TITLE
`dummy(alloca(ZERO))` in hand-compiled tests

### ISSUE THREAD

**Issue by ProExpertProg** [OpenCilk/cheetah#6]
Something I've noticed happens in all hand-compiled tests is the following line, right before the definition of a `__cilkrts_stack_frame`:

```c
dummy(alloca(ZERO));
```

Why is this required? I'm guessing it's maintaining some invariant of the stack pointer, but I'm not sure why exactly. I'm trying to understand it as I work on my own hand-compiled code for the loop frame code.

**Comment by neboat** [comment]
In the handcomp tests, this code is used to ensure the compiler properly saves and restores the stack pointer when it starts and stops executing Cilk code, respectively.

When program execution enters a Cilk function `foo` — that is, a function that contains a `cilk_spawn` — it checks to see whether the execution is currently running on a Cilk worker or the original program thread.  If not, then the execution of `foo` is migrated to a Cilk worker.  When `foo` returns, execution is migrated back to the original program thread.

In order to support this migration back and forth, the stack pointer needs to be saved when execution migrates to a Cilk worker and restored when it migrates back.  But on the handcomp tests, it turns out that compiler doesn't understand what can happen to the stack pointer through these migrations, and it will therefore incorrectly optimize that stack-pointer-handling code.  By including `dummy(alloca(ZERO))`, the compiler is prevented from doing these incorrect optimizations, ensuring that the stack pointer is correctly saved and restored.

This code is only necessary in the handcomp tests.  For real Cilk programs, the compiler knows how to properly maintain the stack pointer for functions that contain `cilk_spawn`.

**Comment by ProExpertProg** [comment]
Thanks! Makes sense
